package com.innercirclesoftware.wkd_api.models

enum class Station(val fullName: String) {
    GRODZISK_MAZ_RADONSKA("Grodzisk Maz. Radońska"),
    GRODZISK_MAZ_JORDANOWICE("Grodzisk Maz. Jordanowice"),
    GRODZISK_MAZ_PIASKOWA("Grodzisk Maz. Piaskowa"),
    GRODZISK_MAZ_OKREZNA("Grodzisk Maz. Okrężna"),
    BRZOZKI("Brzózki"),
    KAZIMIEROWKA("Kazimierówka"),
    MILANOWEK_GRUDOW("Milanówek Grudów"),
    POLESIE("Polesie"),
    PODKOWA_LESNA_ZACHODNIA("Podkowa Leśna Zachodnia"),
    PODKOWA_LESNA_GLOWNA("Podkowa Leśna Główna"),
    PODKOWA_LESNA_WSCHODNIA("Podkowa Leśna Wschodnia"),
    OTREBUSY("Otrębusy"),
    KANIE_HELENOWSKIE("Kanie Helenowskie"),
    NOWA_WIES_WARSZAWSKA("Nowa Wieś Warszawska"),
    KOMOROW("Komorów"),
    PRUSZKOW_WKD("Pruszków WKD"),
    TWORKI("Tworki"),
    MALICHY("Malichy"),
    REGULY("Reguły"),
    MICHALOWICE("Michałowice"),
    OPACZ("Opacz"),
    WARSZAWA_SALOMEA("Warszawa Salomea"),
    WARSZAWA_RAKOW("Warszawa Raków"),
    WARSZAWA_ALEJE_JEROZOLIMSKIE("Warszawa Aleje Jerozolimskie"),
    WARSZAWA_REDUTA_ORDONA("Warszawa Reduta Ordona"),
    WARSZAWA_ZACHODNIA_WKD("Warszawa Zachodnia WKD"),
    WARSZAWA_OCHOTA_WKD("Warszawa Ochota WKD"),
    WARSZAWA_SRODMIESCIE_WKD("Warszawa Śródmieście WKD"),
}